tap "cloudflare/cloudflare"
tap "eth-p/software"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
# In-depth attack surface mapping and asset discovery
brew "amass"
# Official Amazon AWS command-line interface
brew "awscli"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Emacs dependency management
brew "cask"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Cross-platform make
brew "cmake"
# Load/unload environment variables based on $PWD
brew "direnv"
# Modern, maintained replacement for ls
brew "eza"
# Remote repository management made easy
brew "ghq"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Kubernetes package manager
brew "helm"
# Run local Kubernetes cluster in Docker
brew "kind"
# Tool to move from `docker-compose` to Kubernetes
brew "kompose"
# Simple terminal UI for git commands
brew "lazygit"
# Apple Silicon Monitor Top written in Golang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# Run a Kubernetes cluster locally
brew "minikube"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# Open Fortinet client for PPP+TLS VPN tunnel services
brew "openfortivpn"
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@14", link: false
# Object-relational database system
brew "postgresql@17", link: true
# Password generator
brew "pwgen"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# SMART hard drive monitoring
brew "smartmontools"
# Cross-shell prompt for astronauts
brew "starship"
# Subdomain discovery tool
brew "subfinder"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Simplified and community-driven man pages
brew "tldr"
# Manage complex tmux sessions easily
brew "tmuxinator"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript package manager
brew "yarn"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Read system manual pages using bat as the manual page formatter
brew "eth-p/software/bat-extras-batman"
# Terraform
brew "hashicorp/tap/terraform"
# Application uninstaller
cask "appcleaner"
# Chromium based browser
cask "arc"
# Window manager that organizes desktop applications into predefined zones
cask "bentobox"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Remotely access another computer through the Google Chrome browser
cask "chrome-remote-desktop-host"
# Image, video and clipboard optimiser
cask "clop"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Databases and SQL IDE
cask "datagrip"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Online diagram software
cask "drawio"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Download manager with a torrent client
cask "folx"
# HTTP and GraphQL Client
cask "insomnia"
# Automatically ejects external drives
cask "jettison"
# Menu bar manager
cask "jordanbaird-ice"
# Open-source screen recorder built with web technology
cask "kap"
# Open-source keystroke visualiser
cask "keycastr"
# GPU-based terminal emulator
cask "kitty"
# Software for Logitech devices
cask "logi-options+"
# Open-source, KeePass-client and password manager
cask "macpass"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Handy utility to manage and customize the notch area
cask "notchnook"
# System and utility switches
cask "only-switch"
# Collaboration platform for API development
cask "postman"
# IDE for Python programming - Community Edition
cask "pycharm-ce"
# Control your tools with a few keystrokes
cask "raycast"
# Emoji picker optimised for blind people
cask "rocket"
# Displays all open files and sockets in use by all running processes
cask "sloth"
# Design and collaborate in 3D
cask "spline"
# System monitor for the menu bar
cask "stats"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"
# Network protocol analyzer
cask "wireshark"
mas "Boom 3D", id: 1233048948
mas "ColorSlurp", id: 1287239339
mas "DaisyDisk", id: 411643860
mas "DevCleaner", id: 1388020431
mas "Disk Speed Test", id: 425264550
mas "Enchanted", id: 6474268307
mas "Free Ruler", id: 1483172210
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Maccy", id: 1527619437
mas "Magnet", id: 441258766
mas "MonitorControlLite", id: 1595464182
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Redis Insight", id: 6446987963
mas "S3", id: 6447647340
mas "Widgetter", id: 1553223588
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "ahmadalli.vscode-nginx-conf"
vscode "andenetalexander.vim-cheatsheet"
vscode "apollographql.vscode-apollo"
vscode "bodil.prettier-toml"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "chakrounanas.turbo-console-log"
vscode "chouzz.vscode-better-align"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.composer-php-vscode"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "devsense.profiler-php-vscode"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "foxundermoon.shell-format"
vscode "gencer.html-slim-scss-css-class-completion"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "ionutvmi.path-autocomplete"
vscode "janisdd.vscode-edit-csv"
vscode "johnbillion.vscode-wordpress-hooks"
vscode "johnnymorganz.stylua"
vscode "johnpapa.vscode-peacock"
vscode "juggernautjp.less-toml"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "kumar-harsh.graphql-for-vscode"
vscode "leetcode.vscode-leetcode"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "mrmlnc.vscode-scss"
vscode "ms-azuretools.vscode-docker"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-kubernetes-tools.kind-vscode"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.js-debug-nightly"
vscode "ms-vscode.makefile-tools"
vscode "ms-vsliveshare.vsliveshare"
vscode "naumovs.color-highlight"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "orta.vscode-jest"
vscode "pkief.material-icon-theme"
vscode "plex.vscode-protolint"
vscode "pnp.polacode"
vscode "redhat.vscode-yaml"
vscode "redis.redis-for-vscode"
vscode "riazxrazor.html-to-jsx"
vscode "ritwickdey.liveserver"
vscode "shardulm94.trailing-spaces"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "steoates.autoimport"
vscode "styled-components.vscode-styled-components"
vscode "sumneko.lua"
vscode "tabeyti.jenkins-jack"
vscode "timonwong.shellcheck"
vscode "vintharas.learn-vim"
vscode "vscodevim.vim"
vscode "wayou.vscode-todo-highlight"
vscode "william-voyek.vscode-nginx"
vscode "wix.vscode-import-cost"
vscode "wordpresstoolbox.wordpress-toolbox"
vscode "xabikos.javascriptsnippets"
vscode "yogensia.searchwpdocs"
vscode "yzhang.markdown-all-in-one"
vscode "zhuangtongfa.material-theme"
vscode "zxh404.vscode-proto3"

# vim:ft=ruby
