#!/usr/bin/env zsh

# default kubeconfig path
export MERGED_KUBECONFIG=$HOME/.kube/merged-config
export KUBECONFIG=$MERGED_KUBECONFIG

# create merge function
kubeconfig-merge() {
  # ถ้าไม่มี argument ให้แสดงวิธีใช้
  if [[ $# -eq 0 ]]; then
    echo "Usage: kubeconfig-merge [path_to_kubeconfig1] [path_to_kubeconfig2] ..."
    echo "Example: kubeconfig-merge ~/.kube/config ~/.kube/homelab-config"
    return 1
  fi

	local configs=()
	for config in "$@"; do
		if [[ $config =~ '(-v|cache|merged-config)' ]]; then
			continue
		else
			if [[ -f "$config" ]]; then
				configs+="$config"
			else
				echo "Warning: File not found - $config (skipped)"
			fi
		fi
	done

	# ถ้าไม่มีไฟล์ที่ valid เลย ให้หยุดทำงาน
  if [[ ${#configs[@]} -eq 0 ]]; then
    echo "Error: No valid kubeconfig files provided."
    return 1
  fi

	# Dynamically join configs with ':'
	export KUBECONFIG=$(
		IFS=:
		echo "${configs[*]}"
	)
	if [[ $1 =~ '-v' ]]; then; echo "⏳ Merging KUBECONFIG: $KUBECONFIG"; fi

	# Merge and flatten to a single clean config
	echo '# This file was generated by `kubeconfig-merge` command.'
	echo "# merged config files: $KUBECONFIG"
	kubectl config view --merge --flatten >"$HOME/.kube/merged-config"

	# Finally, point KUBECONFIG to the merged file
	export KUBECONFIG="$MERGED_KUBECONFIG"
	if [[ $1 =~ '-v' ]]; then
		echo ""
		echo "✅ Merged kubeconfig saved to: $MERGED_KUBECONFIG"
		echo "📌 Current \$KUBECONFIG: $KUBECONFIG"
	fi
}

# shorten aliases
alias kcm='kubeconfig-merge'

# run on starting shell
# kubeconfig-merge $HOME/.kube/*
